source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '< 1.26.0'
gem 'concurrent-ruby', '< 1.3.8'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal'
gem 'logger'
gem 'benchmark'
gem 'mutex_m'

# `kconv` also left the standard library in 3.4, and is provided by `nkf`.
# CFPropertyList requires it, so CocoaPods fails to even parse the Podfile with
# "cannot load such file -- kconv". xcodeproj declares this itself from 1.26
# onwards, but the pin above holds us below that.
gem 'nkf'
