// AutolinkedNativeModules.g.cs -- contents generated by "react-native run-windows"

using System.Collections.Generic;

namespace Microsoft.ReactNative.Managed
{
    internal static class AutolinkedNativeModules
    {
        internal static void RegisterAutolinkedNativeModulePackages(IList<IReactPackageProvider> packageProviders)
        {

        }
    }
}
