#pragma once
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           7.0.0-build.90+ga9eb6fa111
//       
//       Command:
//           LottieGen -InterfaceBaseName Microsoft.UI.Xaml.Controls.IAnimatedVisual -Language Cppwinrt -WinUIVersion 2.4 -InputFile MotionCorpse-Jrcanest.json
//       
//       Input file:
//           MotionCorpse-Jrcanest.json (38034 bytes created 20:50-08:00 Dec 28 2020)
//       
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "AnimatedVisuals.MotionCorpse_Jrcanest.g.h"

namespace winrt::AnimatedVisuals
{
    // Frame rate:  24 fps
    // Frame count: 82
    // Duration:    3416.7 mS
    namespace implementation
    {
        class MotionCorpse_Jrcanest
            : public MotionCorpse_JrcanestT<MotionCorpse_Jrcanest>
        {
        public:
            // Animation duration: 3.417 seconds.
            static constexpr int64_t c_durationTicks{ 34166666L };

            winrt::Microsoft::UI::Xaml::Controls::IAnimatedVisual TryCreateAnimatedVisual(
                winrt::Windows::UI::Composition::Compositor const& compositor,
                winrt::Windows::Foundation::IInspectable& diagnostics);

            // Converts a frame number to the corresponding progress value.
            double FrameToProgress(double frameNumber);

            // Returns a map from marker names to corresponding progress values.
            winrt::Windows::Foundation::Collections::IMapView<hstring, double> Markers();

            // Sets the color property with the given name, or does nothing if no such property
            // exists.
            void SetColorProperty(hstring const& propertyName, winrt::Windows::UI::Color value);

            // Sets the scalar property with the given name, or does nothing if no such property
            // exists.
            void SetScalarProperty(hstring const& propertyName, double value);
        };
    }

    namespace factory_implementation
    {
        struct MotionCorpse_Jrcanest : MotionCorpse_JrcanestT<MotionCorpse_Jrcanest, implementation::MotionCorpse_Jrcanest>
        {
        };
    }
}
