namespace LottieReactNative
{
    interface ILottieSourceProvider
    {
        Microsoft.UI.Xaml.Controls.IAnimatedVisualSource GetSourceFromName(String name);
        Microsoft.UI.Xaml.Controls.IAnimatedVisualSource GetSourceFromJson(String json);
    }

    [default_interface]
    runtimeclass ReactPackageProvider : Microsoft.ReactNative.IReactPackageProvider
    {
        ReactPackageProvider(ILottieSourceProvider sourceProvider);
    }
}
